[versions]
# kotlin
kotlin = "2.3.0"
serialization = "1.9.0"
coroutines = "1.10.2"
vite = "16.5.0"

# JS
wrapper = "1.0.0-pre.760"

[libraries]
# Kotlin
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}

# JS
wrapper-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "wrapper" }

# build
build-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
build-kotlin-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
build-kotlin-js-plain-objects = { module = "org.jetbrains.kotlin.plugin.js-plain-objects:org.jetbrains.kotlin.plugin.js-plain-objects.gradle.plugin", version.ref = "kotlin" }
build-vite = { module = "io.github.turansky.kfc.application:io.github.turansky.kfc.application.gradle.plugin", version.ref = "vite" }

[plugins]
kotlin-js-objects = { id = "org.jetbrains.kotlin.plugin.js-plain-objects", version.ref = "kotlin" }
vite = { id = "io.github.turansky.kfc.application", version.ref = "vite" }

[bundles]
build = [
    "build-kotlin-multiplatform",
    "build-kotlin-js-plain-objects",
    "build-serialization",
    "build-vite",
]
