package dev.triumphteam.reaper.constant

public enum class SoulReaper(
    public val fullName: String,
    public val image: String? = null,
) {
    AMASCUT("Amascut, the Devourer"),
    AMBASSADOR("The Ambassador"),
    ARAXXI("Araxxi"),
    ARCH_GLACOR("Arch-Glacor"),
    BARROWS_BROTHERS("The Barrows Brothers"),
    BARROWS_RISE_OF_THE_SIX("The Barrows: Rise of the Six", "barrows_brothers"),
    BLACK_STONE_DRAGON("Black stone dragon"),
    CHAOS_ELEMENTAL("Chaos Elemental"),
    COMMANDER_ZILYANA("Commander Zilyana"),
    CORPOREAL_BEAST("Corporeal Beast"),
    CROESUS("Croesus"),
    DAGANNOTH_KINGS("Dagannoth Kings"),
    FLESH_HATCHER_MHEKARNAHZ("Flesh-hatcher Mhekarnahz"),
    GATE_OF_ELIDINIS("The Gate of Elidinis"),
    GENERAL_GRAARDOR("General Graardor"),
    GIANT_MOLE("Giant mole"),
    GREGOROVIC("Gregorovic"),
    HAR_AKEN("Har-Aken"),
    HELWYR("Helwyr"),
    HERMOD("Hermod, the Spirit of War"),
    IVAR("Ivar, King of Bones"),
    KALPHITE_KING("Kalphite King"),
    KALPHITE_QUEEN("Kalphite Queen"),
    KERAPAC("Kerapac, the bound"),
    KING_BLACK_DRAGON("King Black Dragon"),
    KREEARRA("Kree'arra"),
    KRIL("K'ril Tsutsaroth"),
    LEGIONES("Legiones"),
    MAGISTER("The Magister"),
    NAKATRA("Nakatra, Devourer Eternal"),
    NEX("Nex"),
    NEX_ANGEL_OF_DEATH("Nex, Angel of Death"),
    QUEEN_BLACK_DRAGON("Queen Black Dragon"),
    RAKSHA("Raksha, the Shadow Colossus"),
    RASIAL("Rasial, the First Necromancer"),
    REX_MATRIARCHS("Rex Matriarchs"),
    SEIRYU("Seiryu the Azure Serpent"),
    SILVERQUILL("Silverquill, the Dreadhog"),
    SOLAK("Solak, Guardian of the Grove"),
    TELOS("Telos, the Warden"),
    TWIN_FURIES("The Twin Furies"),
    ZUK("TzKal-Zuk"),
    JAD("TzTok-Jad"),
    VINDICTA("Vindicta & Gorvek"),
    VORAGO("Vorago"),
    ZAMORAK("Zamorak, Lord of Chaos"),
    VORKATH("Zemouregal & Vorkath");

    public val id: String = name.lowercase()
}